python /cmlscratch/pan/RLHF_Poisoning/jailbreak_rlhf/train_dpo.py  --exp_no=1 --model="opt-350m" --epoch=10 --sft_epoch=5 --dataset="hh_original" --per=0.05
------
wandb: Currently logged in as: pan27 (pan-27). Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: - Waiting for wandb.init()...wandb: \ Waiting for wandb.init()...wandb: wandb version 0.16.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /cmlscratch/pan/RLHF_Poisoning/wandb/run-20240110_164949-i765wnpn
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run sandy-brook-2
wandb: ‚≠êÔ∏è View project at https://wandb.ai/pan-27/DPO%20Training
wandb: üöÄ View run at https://wandb.ai/pan-27/DPO%20Training/runs/i765wnpn
Traceback (most recent call last):
  File "/cmlscratch/pan/RLHF_Poisoning/jailbreak_rlhf/train_dpo.py", line 105, in <module>
    training_args = TrainingArguments(
                    ^^^^^^^^^^^^^^^^^^
TypeError: TrainingArguments.__init__() missing 1 required positional argument: 'output_dir'
wandb: - 0.008 MB of 0.008 MB uploadedwandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: \ 0.008 MB of 0.008 MB uploadedwandb: | 0.008 MB of 0.008 MB uploadedwandb: / 0.008 MB of 0.008 MB uploadedwandb: - 0.008 MB of 0.008 MB uploadedwandb: üöÄ View run sandy-brook-2 at: https://wandb.ai/pan-27/DPO%20Training/runs/i765wnpn
wandb: Ô∏è‚ö° View job at https://wandb.ai/pan-27/DPO%20Training/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjEyOTE0NjMwMA==/version_details/v0
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240110_164949-i765wnpn/logs
END of SLURM commands
